version: '3.1'

services:

  api-banco:
    image: api-banco
    depends_on:
      - mongo
    network_mode: "host"
    hostname: localhost
    restart: always
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"

  mongo:
    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - /home/forttiori/Docker/Volumes/MongoDB:/data/db


#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#    links:
#      - mongo




