version: '3.1'

services:

  api-banco:
    image: api-banco
    depends_on:
      - mongo
    network_mode: "host"
    hostname: localhost
    restart: always
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /home/forttiori/Docker/Volumes/MongoDB:/data/db




