server:
  port: 8080

spring:
  data:
    mongodb:
      authentication-database: admin
      database: banco
      host: localhost
      port: 27017
#      password: password
#      username: root


